
# AUTOMATICALLY GENERATED BY 'RECON':
# * DO NOT EDIT THIS MODULE MANUALLY.
# * DO NOT COMMIT THIS MODULE TO YOUR GIT REPOSITORY

__all__ = [
    '__version__',
    '__version_post__',
    '__version_commit__',
    '__version_date__',
    '__version_dirty__',
    '__build_date__',
    '__build_status__'
]

__version__ = '1.1.2'
__version_post__ = ''
__version_commit__ = ''
__version_date__ = '2015-10-14 15:01:35 +0000'
__version_dirty__ = True
__build_date__ = '2016-03-28'
__build_time__ = '14:37:12.432857'
__build_status__ = 'release' if not __version_post__ \
    and not __version_commit__ \
    and not __version_dirty__ \
    else 'development'
